default: &default
  adapter: sqlite3
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: storage/development.sqlite3

test:
  <<: *default
  database: storage/test.sqlite3

production:
  primary:
    <<: *default
    database: <%= ENV.fetch("DB_PATH", "storage") %>/production.sqlite3
  queue:
    <<: *default
    database: <%= ENV.fetch("DB_PATH", "storage") %>/production_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: <%= ENV.fetch("DB_PATH", "storage") %>/production_cable.sqlite3
    migrations_paths: db/cable_migrate
