shared:
  apple:
    key_id: <%= Rails.application.credentials.dig(:action_push_native, :apns, :key_id) %>
    encryption_key: <%= Rails.application.credentials.dig(:action_push_native, :apns, :encryption_key)&.dump %>
    team_id: <%= Rails.application.credentials.dig(:action_push_native, :apns, :team_id) %>
    topic: <%= Rails.application.credentials.dig(:action_push_native, :apns, :topic) %>
